name: Rhyme Backend CI/CD
on:
  push
jobs:
  CICD:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, fileinfo, gd, intl, mbstring, mysqli, openssl, xml, zip, opcache
        env:
          fail-fast: true
      - name: CICD
        run: |
          chmod +x ./.github/workflows/cicd.sh \
          && ./.github/workflows/cicd.sh
        shell: bash
